{
  # Generated by tools/module-update.py; do not edit by hand.
  # Structure: <category>.<module> = { nixos, home };
  # Note: options/options.nix is assumed to always exist

  core = {
  };

  desktop = {
  };

  server = {
  };

  pentesting = {
  };

}
