{
  # Generated by tools/module-update.py; do not edit by hand.
  # Structure: <category>.<module> = { nixos, home };
  # Note: options/options.nix is assumed to always exist

  core = {
    boot = {
      nixos = true;
      home = false;
    };
    impermanence = {
      nixos = true;
      home = false;
    };
    localisation = {
      nixos = true;
      home = false;
    };
    lsd = {
      nixos = false;
      home = true;
    };
    nvf = {
      nixos = false;
      home = true;
    };
    plymouth = {
      nixos = true;
      home = false;
    };
    polkit = {
      nixos = true;
      home = false;
    };
    shell = {
      nixos = true;
      home = true;
    };
    starship = {
      nixos = false;
      home = true;
    };
    stylix = {
      nixos = true;
      home = false;
    };
    user = {
      nixos = true;
      home = false;
    };
    zfs = {
      nixos = true;
      home = false;
    };
  };

  desktop = {
  };

  server = {
  };

  pentesting = {
  };

}
