{ ctx }:
with ctx;
assert
  qnix.featureNames == [
    "appearance.fonts"
    "appearance.stylix"
    "desktop.clipboard"
    "desktop.displaymanager"
    "desktop.hyprland"
    "desktop.hyprland.keybinds"
    "desktop.hyprland.monitors"
    "desktop.hyprland.rules"
    "desktop.hyprland.special-workspaces"
    "desktop.lock"
    "desktop.noctalia"
    "desktop.screenshots"
    "desktop.sound"
    "desktop.terminal"
    "desktop.wayland"
    "desktop.xdg-folders"
    "hardware.bluetooth"
    "hardware.laptop"
    "hardware.power-management"
    "hardware.thunderbolt"
    "network.addressing"
    "network.firewall"
    "network.networkmanager"
    "persist"
    "security.gnome-keyring"
    "security.gpg"
    "security.polkit"
    "security.sops"
    "security.yubikey"
    "shell.fish"
    "shell.packages"
    "shell.starship"
    "shell.zsh"
    "storage.impermanence"
    "storage.zfs"
    "system.boot"
    "system.localisation"
    "system.plymouth"
    "system.users"
  ];
assert
  qnix.profileNames == [
    "appearance"
    "base"
    "hyprland"
    "impermanence"
    "laptop"
    "secrets"
    "workstation"
  ];
pkgs.runCommand "qnix-repository-check" { } "touch $out"
